enter = input("digite algo ")
num = enter.isnumeric()
alnum = enter.isalnum()
space = enter.isspace()
alpha = enter.isalpha()
upper = enter.isupper()
lower = enter.islower()
title = enter.istitle()

print("O dado digitado é numérico?", num)
print("O dado digitado é alfanumérico?", alnum)
print("O dado digitado é um espaço?", space)
print("O dado digitado é alfabético?", alpha)
print("O dado digitado é totalmente caixa alta", upper)
print("O dado digitado é totalmente caixa baixa", lower)
print("O dado digitado possui o 1º caractere em caixa alta?", title)
